export const knownLangs = [
  "C/C++",
  "C#",
  "Java",
  "Python",
  "Haskell",
  "TypeScript",
  "JavaScript",
  "HTML",
  "CSS",
  "Bash",
  "PowerShell",
  "SQL",
];

export const knownTools = [
  "Windows",
  "Linux",
  "MacOS",
  "Visual Studio Code",
  "Visual Studio",
  "IntelliJ",
  "Android Studio",
  "AWS",
  "GitHub/GitLab",
  "NextJS",
  "NodeJS",
  "React",
  "ExpressJS",
];

export const softSkills = [
  "Communication",
  "Problem Solving",
  "Time Management",
  "Teamwork",
  "Adaptability",
  "Attention to Detail",
  "Critical Thinking",
  "Empathy",
  "Self-Motivation",
  "Ethical Awareness",
  "Continuous Learning",
  "Documentation",
  "Cultural Sensitivity",
  "Presentation Skills",
  "Risk Management",
  "Conflict Resolution",
  "Leadership",
];

export const hardSkills = [
  "Programming Languages",
  "REST API",
  "DevOps",
  "Web Development",
  "Database Management",
  "Software Testing",
  "Version Control",
  "Algorithms and Data Structures",
  "Operating Systems",
  "Cloud Computing",
  "Mobile App Development",
  "UI/UX Design",
  "Software Architecture",
  "Agile and Scrum Methodologies",
  "Compiler Design",
  "Embedded Systems",
];

export const completedCourses = [
  "Software Engineering",
  "Algorithms & Complexity",
  "Computer Systems Programming",
  "Operating Systems",
  "Advanced Computer Systems Programming",
  "Web Development",
  "Advanced Java",
  "Social, Ethical, & Legal Implications of Computing",
  "Code Reading & Review",
  "Database Management",
  "Functional Programming",
  "Data Structures",
  "Principals of Programming Languages",
  "Programming Methods & Software Implementation",
];
